### ISSUE TITLE
No se ve la imagen.

### ISSUE THREAD

**Issue by pposca** [AdrianaY/DAW2-M9#1]
![image](https://user-images.githubusercontent.com/168123/101802119-6467bb00-3b0f-11eb-87ed-07f8ff8e376d.png)

![image](https://user-images.githubusercontent.com/168123/101802031-45692900-3b0f-11eb-8dca-b6d823420ee7.png)

**Comment by AdrianaY** [comment]
He cambiado la extensión de la imagen a letras minúsculas para que coincida con el html.
