### ISSUE TITLE
Proyecto 2a: La parte de abajo no queda como debería

### ISSUE THREAD

**Issue by pposca** [AdrianaY/DAW2-M9#2]
![image](https://user-images.githubusercontent.com/168123/102520279-d0a86880-4093-11eb-9b64-98f020d2c3a9.png)

Debería ser:
![image](https://user-images.githubusercontent.com/168123/102520306-dd2cc100-4093-11eb-9d98-b5ef7609da16.png)

**Comment by AdrianaY** [comment]
Ya está arreglado.
